name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build & Test
        run: ./gradlew --no-daemon clean test

      # Install Allure CLI to generate the static site
      - name: Install Allure CLI
        run: |
          sudo npm i -g allure-commandline --unsafe-perm=true
          allure --version

      # Generate the pretty HTML report from test results
      - name: Generate Allure Report
        if: always()
        run: |
          mkdir -p build/allure-results
          allure generate --clean build/allure-results --output allure-report

      # Publish to GitHub Pages
      - name: Upload Allure Report for Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy-pages:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
