name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
        with:
          min-wrapper-count: 1
          allow-snapshots: false
        continue-on-error: true  # avoid failing on transient network errors

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build & Test
        run: ./gradlew --no-daemon clean build

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          if-no-files-found: warn
          path: |
            **/build/test-results/test/*.xml
            **/build/reports/tests/test/**
